---
title: "The Stream Condition Index: A Multi-Indicator Tool For Enhancing Environmental Management Communication"
output: 
  bookdown::word_document2:
    reference_docx: my_styles.docx
# bibliography: refs.bib
author: 'Marcus W. Beck (marcusb@sccwrp.org), Raphael D. Mazor (raphaelm@sccwrp.org), Kenneth C. Schiff (kens@sccwrp.org'
urlcolor: blue
link-citations: true
---

```{r setup, echo = F, warning = F, message = F, results = 'hide'}
# figure path, chunk options
knitr::opts_chunk$set(fig.path = 'figs/', warning = F, message = F, echo = F, cache = T, dev.args = list(family = 'serif'), dpi = 300, warning = F, out.width = '100%', cache.path = 'manu_draft_cache/',
  fig.process = function(x) {
  x2 = sub('-\\d+([.][a-z]+)$', '\\1', x)
  if (file.rename(x, x2)) x2 else x
  })

# libraries
library(Jabbrev)

# # extract bib entries from online
# bib_scrp('outline.Rmd', 'refs.bib')
```

# Introduction

* A cornerstone of the Clean Water Act is to restore and maintain the chemical, physical, and biological integrity of the Nation's waters. (CWA)
     * 	All three lines of evidence are necessary to ensure aquatic life beneficial uses are fully supported (CWA §305b, 303d)
     * 	Monitoring physical habitat integrity is necessary to ensure all of the necessary environmental niches are present to support aquatic life (Poff or other Keystone PHab ref)
     * 	Monitoring chemical integrity is necessary because even with suitable physical habitat, unbalanced chemical composition can impair aquatic life (EPA Green Book)
     * 	Monitoring biological integrity, closest to the beneficial use, is necessary because unmeasured habitat or chemical water quality can impair balanced ecosystems (Stoddard, Ode). 
*	A tremendous amount of effort is spent monitoring all three lines of evidence
     * 	Cite some programs here that spend a lot of effort and money on the triad (EPA EMAP, PSA, SMC, Ohio, Maryland, etc)
*	A common challenge when monitoring multiple indicators is how to communicate the complex physical, chemical, and biological results in a scientifically rigorous, repeatable, yet readily understandable way to non-scientists. (NRC)
     * 	Most environmental managers and decision makers are not scientists and don’t understand the intricate, nuanced details of ecological data
     * 	Rarely are ecological data black and white, so many of decisions asked of mangers are made in the “grey zone” (pick from thousands of refs)
     * 	This is particularly true when the different lines of evidence are not in complete agreement
*	Currently, there are many examples of how to effectively communicate single lines of evidence
     * 	IBIs (Karr)
     * 	O/E (Hawkins)
     * 	Combined IBI and O/E (Mazor)
     * 	BRI (Smith) or AMBI (Borja) –if you want to include marine
*	Ideally, scientists would combine multiple indicators into a single index, although this rarely occurs
     * 	Honestly, can’t think of a good one.  Maybe you have an example.  To me, the SQO is perhaps the best example
     * 	Most frequently, the three indicators are individually simplified and presented in groups, leaving managers to decide which is most important.
*	The goal of this study was to develop the Stream Condition Index, a single index that combines physical, chemical, and biological indicators into a scientifically rigorous, yet easy to understand tool for management decision making.

# Methods

## General Approach

*	The SQI uses a stressor-response conceptual approach
     * 	Stressors include chemistry and physical habitat
          *	PHab can sometimes be considered a response, but we treat it as a stressor
     * 	Response includes benthic invertebrates and algae
          *	Multiple taxa groups are critical for balanced outcomes
     * 	Focused on So Cal
          *	Lots of data
          *	A wide range of stress and response
          *	Mandate for decision making
*	Philosophical drivers
     * 	Simple single answer at the end to support management decision making (set up for categorical scores at the end)
     * 	Must be easily deconstructed so scientists can quickly glean what stressors or responses are driving the final score (Set up for the flowchart and for the web site)
     * 	The primary pursuit is stream biological condition (set up to the stressor modeling)

## Stressor Components

*	Chemical Index
     * 	N, P, Cond
     * 	Describe modeling
     * 	Maybe include details as supplemental material?
*	Physical Habitat Index 
     * 	General description (Cite PIBI)
     * 	CRAM
     * 	PHab

## Response Components

*	Invertebrate index, CSCI
     * 	General description (Cite Mazor)
     * 	
*	Algae index, ASCI
     * 	General description (Cite Theroux)

## Stream Condition Index

*	Flow chart description
*	Combining stressors
*	Combining responses
*	Combining stress and Response
*	Linking final score to management actions (the categorical descriptions)

## Application

*	SMC data set
*	Evaluation parameters/Performance metrics
*	Web app (or leave this for discussion

# Results

*	SQI performance metrics
     * 	Precision
     * 	Any others?
*	Percent So Cal stream miles or site frequency in each category
     * 	As a set up for the value of the categorical scoring
*	Overall agreement among stressor indicators
     * 	As a set up for do we need multiple indicators?
*	Overall agreement among response indicators
     * 	As a set up for do we need multiple indicators?
*	SQI trends either overall or at example sites

# Discussion

*	The SQI provides a management tool that is easily understandable
     * 	The categories are descriptive of the outcomes
     * 	Particularly important in a place like southern California where priority setting is critical
*	The SQI is technically robust and is easily deconstructed for scientists to decipher details
     * 	Can quickly reach individual stressor or response values/data
     * 	
*	The SQI utilizes a relatively new approach for scoring stress
     * 	Examples where pPIBI or pChem exist in the literature
     * 	How the RF model varies relative to other chemical magniture&frequency stressor scores (i.e, Canadian tool, RB3)
     * 	No previous PHab tool
*	Drawbacks to the SQI
     * 	Does not include all stressors (i.e., all chemicals, flow modification, etc)
     * 	Does not include all responses (i.e., vertebrates, etc)
     * 	The approach can/cannot incorporate these variables in other places/with more data?
*	The utility of the SQI is enhanced with the web application
     * 	Drop and calculate
     * 	Spatial scaling 
     * 	Instantaneous data dives
     * 	The restoration calculator tool
     * 	(optional) Linkage to the SCAPE for “restoration” and RSCA tools for “causal assessment” categories
*	 


